name: "Podcast Generator"
author: "Reevan christopher cutinho"
description: "Generates a feed for a podcast"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icons: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiters email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The commitores name
    required: true
    defualt: ${{github.actor}}